name: "unet_savedmodel"
platform: "tensorflow_savedmodel"
max_batch_size: 1
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 256, 256, 3 ]
  }
]
output [
  {
    name: "sigmoid"
    data_type: TYPE_FP32
    dims: [ 256, 256, 2 ]
    label_filename: "unet_labels.txt"
  }
]
